### ISSUE TITLE
auro-calendar initial release

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-calendar#1]
## Initial release 

The following items are to be included with the first release of the `auro-calendar`, all PRs are to be from the feature branch to `v1.0-rc` branch.

Please refer to [this document](https://www.figma.com/file/HKtbt2KXrM1pnayGtYt9KM/Flight-Search-Build-Strategy?node-id=0%3A1) for background on how this component will be architected.

- [x] #2 
- [ ] https://github.com/AlaskaAirlines/auro-calendar/issues/4
- [ ] Review the A11Y needs.

### After we are comfortable with the scope we can begin to create it.
- [x] #3 
- [ ] Add to the doc site

#### Notes for the MVP version:
The calendar will not have prices
The calendar when opened by the input will only show one month
There will be separate inputs for departure and return and each will open an instance of the auro-calendar

**Comment by blackfalcon** [comment]
Work moved to collaborative OSS discussion.
