### ISSUE TITLE
Prev/next chevrons are not displaying on calendar in Firefox

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-calendar#37]
## Describe the bug

View original issue for reference:
- https://github.com/AlaskaAirlines/auro-datepicker/issues/84

The chevrons used to change the month on `auro-calendar` are not displaying correctly in Firefox.

## To Reproduce

1. Go to https://auro.alaskaair.com/components/auro/datepicker
1. Click inside the datepicker to open the calendar
1. See error

## Expected behavior

Chevrons are displayed across all browsers.

## Screenshots

![Screen Shot 2023-01-24 at 3 10 23 PM](https://user-images.githubusercontent.com/55807669/214441603-cbd56503-44ac-4828-824d-28f36d2ef0b5.png)

## Desktop (please complete the following information):

 - OS: iOS
 - Browser: Firefox

**Comment by jordanjones243** [comment]
This issue is coming from the use of `-webkit-mask-box-image` within the `style.scss` file to display the chevron icons.

**Comment by blackfalcon** [comment]
See comments here. 

https://github.com/AlaskaAirlines/auro-datepicker/issues/84#issuecomment-1402814042
